import LeanNCD.Acset.Io
open Lean Elab Command

/-!
# Task 5: Python-fixture cross-check (genuine interop, byte-for-byte)

The fixtures in `test/Acset/fixtures/*.csv` were generated by the **Python**
`acset.csv_io.write_sbr` applied to `tests/test_acset_csv.py:_two_equation_sbr()`
(2 equations, 6 arrays incl. a `linear` op / `reals` dtype / a `bias`, multiple
array_axes, and samples). They use CRLF (`\r\n`) line terminators, exactly as
Python's `csv` module emits (including a trailing terminator on the last row).
They are treated as GROUND TRUTH and must not be regenerated or edited.

This cross-check reads the five fixtures with `IO.FS.readFile` at elaboration
(which performs no newline translation, so CRLF is preserved), runs Lean's
`readSBr` on them, then `writeSBr` the result and asserts each file is
reproduced **byte-for-byte**. This proves (a) Lean parses the exact Python CSV
and (b) Lean's `writeSBr` emits the exact Python bytes — column order,
encodings, and CRLF — without any hand-transcribed expected instance.

CWD note: `lake build` / `lake env lean` run with the package dir (`leanncd`)
as CWD, so the relative path `test/Acset/fixtures/<f>` resolves.
-/

namespace LeanNCD.Acset

run_cmd liftTermElabM do
  let files := ["axis_sizes.csv", "equations.csv", "arrays.csv", "array_axes.csv", "samples.csv"]
  let dir := "test/Acset/fixtures"
  -- read the Python-generated fixture (raw bytes, no newline translation)
  let pairs ← files.mapM (fun f => do
    let content ← IO.FS.readFile s!"{dir}/{f}"
    return (f, content))
  -- (a) Lean reads the Python CSV
  match readSBr pairs with
  | .error e => throwError s!"readSBr FAILED on Python fixture: {e}"
  | .ok inst =>
      -- (b) writeSBr reproduces the Python bytes exactly, per file.
      -- `writeSBr` is `Except CsvError` since 2026-07-30 (audit finding #17); a Python fixture that
      -- Lean cannot re-serialize is itself a real failure, so surface it rather than defaulting.
      let written ← match writeSBr inst with
        | .ok fs   => pure fs
        | .error e => throwError s!"writeSBr FAILED on an instance read from a Python fixture: {e}"
      for (f, want) in pairs do
        let got := (written.find? (·.1 == f)).map (·.2) |>.getD "<missing>"
        unless got == want do
          throwError s!"{f}: writeSBr ≠ Python fixture\n--- got ---\n{repr got}\n--- want ---\n{repr want}"
  pure ()

end LeanNCD.Acset
